//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocateClassroom
    {
        public int AllocateClassroomId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Room { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> Frm { get; set; }
        public Nullable<System.TimeSpan> Too { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Day Day1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
