//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseAssignTeachers = new HashSet<CourseAssignTeacher>();
            this.EnrollInACourses = new HashSet<EnrollInACourse>();
            this.StudentResults = new HashSet<StudentResult>();
            this.AllocateClassrooms = new HashSet<AllocateClassroom>();
        }
    
        public int CourseId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Description { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Semester { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Semester Semester1 { get; set; }
        public virtual ICollection<CourseAssignTeacher> CourseAssignTeachers { get; set; }
        public virtual ICollection<EnrollInACourse> EnrollInACourses { get; set; }
        public virtual ICollection<StudentResult> StudentResults { get; set; }
        public virtual ICollection<AllocateClassroom> AllocateClassrooms { get; set; }
    }
}
