//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.AllocateClassrooms = new HashSet<AllocateClassroom>();
        }
    
        public string Room1 { get; set; }
    
        public virtual ICollection<AllocateClassroom> AllocateClassrooms { get; set; }
    }
}
