//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.CourseAssignTeachers = new HashSet<CourseAssignTeacher>();
        }
    
        public int TeacherId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<double> CreditToBeTaken { get; set; }
    
        public virtual ICollection<CourseAssignTeacher> CourseAssignTeachers { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation1 { get; set; }
    }
}
